# Generated by Django 3.2.4 on 2021-06-12 17:59

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('gramps_title', models.CharField(max_length=32)),
                ('residence', models.CharField(max_length=128)),
                ('house_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100, message='Should not be above 100, You do not live in Heaven')])),
                ('date_started', models.DateTimeField()),
                ('residence_description', models.TextField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
